spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    inetutils:
      default-ip-address: 127.0.0.1
server:
  port: 9006
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.inetutils.default-ip-address}:${spring.application.instance-id:${server.port}}